exclude: '\.SRCINFO|\.patch$'
repos:
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
        types: [file]
        files: PKGBUILD|\.(install|sh)$
        args: [-s, bash, -e, 'SC2034,SC2154,SC2164']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
